Added year_report endpoint
Code4SA/umibukela pull request #44
Opened 2016-11-24 14:50 UTC by smmbll

2016-11-24 16:21 UTC, longhotsummer commented on umibukela/healthe/views.py
> +    end_date = arrow.get('%s-12-31' % year).date()
We need to be careful to honour the agreement Health-E has with the dept not to publicly release data until a month after it has been captured. `end_date` should be no later than 4 weeks before today. eg.

```python
cutoff = date.today() - timedelta(weeks=4)
if end_date > cutoff:
    end_date = cutoff
```

2016-11-24 16:22 UTC, longhotsummer requested changes
Looks good, just the minor change.

2016-11-24 16:22 UTC, longhotsummer commented on umibukela/healthe/views.py
> +    end_date = arrow.get('%s-12-31' % year).date()
We need to be careful to honour the agreement Health-E has with the dept not to publicly release data until a month after it has been captured. `end_date` should be no later than 4 weeks before today. eg.

```python
cutoff = date.today() - timedelta(weeks=4)
if end_date > cutoff:
    end_date = cutoff
```

2016-11-24 16:23 UTC, longhotsummer commented on umibukela/healthe/views.py
> +    end_date = arrow.get('%s-12-31' % year).date()
Please sanity check my logic here, it has been a long day :)

2016-11-25 06:26 UTC, smmbll commented on umibukela/healthe/views.py
> +    end_date = arrow.get('%s-12-31' % year).date()
is it a calendar month, i.e. 30 days, or four weeks? i've altered it to reflect your suggestion but wanted to be sure.

2016-12-01 12:02 UTC, longhotsummer approved these changes

2016-12-01 12:02 UTC, longhotsummer commented
looks good!

2016-12-06 09:30 UTC, merged